In [9]:
import torch

In [10]:
torch.tensor([1,2])

tensor([1, 2])

In [11]:
torch.tensor([1.,2.], requires_grad=True)

tensor([1., 2.], requires_grad=True)

In [12]:
torch.tensor([1.,2.], requires_grad=True).detach()

tensor([1., 2.])

In [13]:
a = torch.tensor([1,2])
b = torch.tensor([3,4])
print(a + b)

tensor([4, 6])


In [14]:
torch.tensor([1,2]) + torch.tensor([3,4])

tensor([4, 6])

In [15]:
# torch.randn(4,5) + torch.randn(5,4)

In [16]:
a = torch.tensor([1,2])
b = torch.tensor([3,4])
print(a * b)

tensor([3, 8])


In [17]:
torch.zeros((3, 3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [18]:
torch.rand((3, 3))

tensor([[0.8007, 0.1800, 0.6817],
        [0.7671, 0.1013, 0.8516],
        [0.8827, 0.5688, 0.0612]])

In [19]:
torch.ones((3, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [20]:
torch.eye(5, 5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [21]:
x = torch.tensor([1, 2, 3])
print(x.pow(2))

tensor([1, 4, 9])


In [22]:
a = torch.tensor([3,1])
b = torch.tensor([2,5])
print(a * b)

tensor([6, 5])


In [23]:
a = torch.rand(2, 5)
b = torch.rand(5, 3)
print(a.mm(b))

tensor([[1.6989, 1.0253, 1.3717],
        [1.5169, 1.0881, 1.5305]])


In [24]:
x = torch.tensor([[1., 0.], [-1., 1.]], requires_grad=True)
z = x.pow(2).sum()
z.backward()
print(x.grad)

tensor([[ 2.,  0.],
        [-2.,  2.]])
